server:
  port: 8080

spring:
    datasource:
        name: test
        url: jdbc:mysql://120.79.90.216:3306/surprise?characterEncoding=UTF-8
        username: root
        password: 9011235
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    freemarker:
      cache: false
      settings:
        template_update_delay: 0



mybatis:
  mapper-locations: mapper/**/*Mapper.xml
  type-aliases-package: com.shimaoxin.surprise.model.*

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true

